# Generated by Django 3.2.3 on 2021-05-29 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=400)),
                ('content', models.TextField()),
                ('time', models.DateTimeField()),
                ('image', models.ImageField(null=True, upload_to='media/Banner')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='media/Games')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('image', models.ImageField(null=True, upload_to='media/Sliders')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ladders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='media/Ladders')),
                ('console', models.CharField(max_length=100)),
                ('maxmembers', models.CharField(default='11', max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('season', models.IntegerField(default=0)),
                ('teams', models.IntegerField(default=0)),
                ('matches_played', models.IntegerField(default=0)),
                ('rules', models.TextField()),
                ('playoff_info', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('rank', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tlou.games')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='media/News')),
                ('Description', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='sliders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=400)),
                ('SubHeading', models.CharField(max_length=400, null=True)),
                ('link', models.CharField(default='#', max_length=400)),
                ('image', models.ImageField(null=True, upload_to='media/Sliders')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(default='#', max_length=400)),
                ('faicon', models.CharField(default='fa-facebook', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userdtl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpass', models.CharField(default='', max_length=50)),
                ('add1', models.CharField(default='', max_length=500)),
                ('add2', models.CharField(default='', max_length=500)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('zipcode', models.IntegerField(default=0)),
                ('tpass', models.CharField(default='', max_length=500)),
                ('psn', models.CharField(default='', max_length=500)),
                ('xbl', models.CharField(default='', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/Teams')),
                ('Win', models.IntegerField(default=0)),
                ('Lose', models.IntegerField(default=0)),
                ('Trophies', models.IntegerField(default=0)),
                ('ladder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tlou.ladders')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('Leader', 'Leader'), ('Captain', 'Captain'), ('Member', 'Member')], default='Member', max_length=34)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tlou.team')),
            ],
        ),
    ]
