# Generated by Django 3.2.3 on 2021-05-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ladders',
            name='teams',
        ),
        migrations.AddField(
            model_name='ladders',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, to='tlou.Team'),
        ),
    ]
