# Generated by Django 3.2.3 on 2021-05-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0002_auto_20210529_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdtl',
            name='invitation',
            field=models.ManyToManyField(blank=True, null=True, to='tlou.Team'),
        ),
    ]
