# Generated by Django 3.2.3 on 2021-05-30 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0003_userdtl_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(default='Best of 1', max_length=34)),
                ('players', models.CharField(default='3v3', max_length=34)),
                ('time', models.DateTimeField()),
                ('match_ladder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ladders_match', to='tlou.ladders')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team_A', to='tlou.team')),
                ('team_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Team_B', to='tlou.team')),
            ],
        ),
    ]
