# Generated by Django 3.2.3 on 2021-05-30 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0004_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='about',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='founded_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='match_request',
            field=models.ManyToManyField(blank=True, null=True, to='tlou.Matches'),
        ),
    ]
