# Generated by Django 3.2.3 on 2021-05-31 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0005_auto_20210530_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
