# Generated by Django 3.2.3 on 2021-06-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0007_alter_matches_team_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='members_list',
            field=models.TextField(null=True),
        ),
    ]
