# Generated by Django 3.1.5 on 2021-06-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0008_matches_members_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='result',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matches',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='team',
            name='Lose',
        ),
        migrations.AddField(
            model_name='team',
            name='Lose',
            field=models.ManyToManyField(related_name='Loser', to='tlou.Matches'),
        ),
        migrations.RemoveField(
            model_name='team',
            name='Win',
        ),
        migrations.AddField(
            model_name='team',
            name='Win',
            field=models.ManyToManyField(related_name='Winner', to='tlou.Matches'),
        ),
    ]
