# Generated by Django 3.1.5 on 2021-06-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0011_auto_20210601_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='Lose',
        ),
        migrations.AddField(
            model_name='team',
            name='Lose',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='team',
            name='Win',
        ),
        migrations.AddField(
            model_name='team',
            name='Win',
            field=models.IntegerField(default=0),
        ),
    ]
