# Generated by Django 3.2.3 on 2021-06-02 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0013_auto_20210602_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='result_team_1',
            new_name='result',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='result_team_2',
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1_report', models.TextField(blank=True, null=True)),
                ('team_2_report', models.TextField(blank=True, null=True)),
                ('dispute', models.TextField(blank=True, null=True)),
                ('dispute_proof_1', models.CharField(blank=True, max_length=300, null=True)),
                ('dispute_proof_2', models.CharField(blank=True, max_length=300, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MatchReport', to='tlou.matches')),
            ],
        ),
    ]
