# Generated by Django 3.2.3 on 2021-06-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0014_auto_20210602_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='dispute',
            new_name='dispute_text_1',
        ),
        migrations.AddField(
            model_name='report',
            name='dispute_text_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='winner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
