# Generated by Django 3.2.3 on 2021-06-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0015_auto_20210602_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='winner_id',
            new_name='winner_id_1',
        ),
        migrations.AddField(
            model_name='report',
            name='winner_id_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
