# Generated by Django 3.2.3 on 2021-06-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0018_auto_20210602_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='streak',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdtl',
            name='steam',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userdtl',
            name='twitch',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userdtl',
            name='twitter',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userdtl',
            name='youtube',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
