# Generated by Django 3.2.3 on 2021-06-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0019_auto_20210602_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='streak',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
