# Generated by Django 3.2.3 on 2021-06-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0020_alter_team_streak'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Trophies',
            new_name='bronze_trophy',
        ),
        migrations.AddField(
            model_name='team',
            name='gold_trophy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='silver_trophy',
            field=models.IntegerField(default=0),
        ),
    ]
