# Generated by Django 3.1.5 on 2021-06-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0021_auto_20210603_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='crown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='rating',
            field=models.IntegerField(default=1000),
        ),
    ]
