# Generated by Django 3.1.5 on 2021-06-03 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0022_auto_20210603_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
