# Generated by Django 3.2.3 on 2021-06-04 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0024_auto_20210603_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='banner',
            field=models.ImageField(default='media/Team/profile.png', null=True, upload_to='media/Teams'),
        ),
        migrations.AddField(
            model_name='userdtl',
            name='team_left',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='ladder',
            field=models.ForeignKey(blank=True, default='media/Team/profile.png', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tlou.ladders'),
        ),
    ]
