# Generated by Django 3.2.3 on 2021-06-04 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0025_auto_20210604_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, default='media/Team/profile.png', null=True, upload_to='media/Teams'),
        ),
        migrations.AlterField(
            model_name='team',
            name='ladder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tlou.ladders'),
        ),
    ]
