# Generated by Django 3.2.3 on 2021-06-05 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0032_maps'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_matches', to='tlou.matches'),
        ),
        migrations.AddField(
            model_name='matches',
            name='cancel_request_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matches',
            name='cancel_request_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='maps',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_host', to='tlou.team'),
        ),
    ]
