# Generated by Django 3.2.3 on 2021-06-05 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0034_maplist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplist',
            name='ladder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_ladders', to='tlou.ladders'),
        ),
    ]
