# Generated by Django 3.2.3 on 2021-06-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0037_auto_20210606_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplist',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/maps'),
        ),
        migrations.AddField(
            model_name='maps',
            name='img_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
