# Generated by Django 3.2.3 on 2021-06-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0039_alter_matches_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='rating_per_match',
            field=models.TextField(default='[]'),
        ),
    ]
