# Generated by Django 3.2.3 on 2021-06-07 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0040_team_rating_per_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTeamTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_1', models.CharField(max_length=196)),
                ('proof_2', models.CharField(max_length=196)),
                ('proof_3', models.CharField(max_length=196)),
                ('msg', models.TextField()),
                ('claims', models.BooleanField()),
                ('reported', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_two_team', to='tlou.matches')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTeamOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_1', models.CharField(max_length=196)),
                ('proof_2', models.CharField(max_length=196)),
                ('proof_3', models.CharField(max_length=196)),
                ('msg', models.TextField()),
                ('claims', models.BooleanField()),
                ('reported', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_one_team', to='tlou.matches')),
            ],
        ),
    ]
