# Generated by Django 3.2.3 on 2021-06-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0041_reportteamone_reportteamtwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportteamone',
            name='msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportteamone',
            name='proof_1',
            field=models.CharField(blank=True, max_length=196, null=True),
        ),
        migrations.AlterField(
            model_name='reportteamone',
            name='proof_2',
            field=models.CharField(blank=True, max_length=196, null=True),
        ),
        migrations.AlterField(
            model_name='reportteamone',
            name='proof_3',
            field=models.CharField(blank=True, max_length=196, null=True),
        ),
        migrations.AlterField(
            model_name='reportteamtwo',
            name='msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportteamtwo',
            name='proof_1',
            field=models.CharField(blank=True, max_length=196, null=True),
        ),
        migrations.AlterField(
            model_name='reportteamtwo',
            name='proof_2',
            field=models.CharField(blank=True, max_length=196, null=True),
        ),
        migrations.AlterField(
            model_name='reportteamtwo',
            name='proof_3',
            field=models.CharField(blank=True, max_length=196, null=True),
        ),
    ]
