# Generated by Django 3.2.3 on 2021-06-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0042_auto_20210607_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladders',
            name='minmembers',
            field=models.IntegerField(default='3'),
        ),
        migrations.AlterField(
            model_name='ladders',
            name='maxmembers',
            field=models.IntegerField(default='11'),
        ),
    ]
