# Generated by Django 3.2.3 on 2021-06-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0045_matches_disputed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportteamone',
            name='claims',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportteamone',
            name='reported',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='reportteamtwo',
            name='claims',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportteamtwo',
            name='reported',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
