# Generated by Django 3.2.3 on 2021-06-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0046_auto_20210608_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdtl',
            name='steam',
        ),
        migrations.RemoveField(
            model_name='userdtl',
            name='xbl',
        ),
        migrations.RemoveField(
            model_name='userdtl',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='userdtl',
            name='bronze_trophy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdtl',
            name='gold_trophy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdtl',
            name='silver_trophy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdtl',
            name='add1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userdtl',
            name='add2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userdtl',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdtl',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
