# Generated by Django 3.2.3 on 2021-06-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0047_auto_20210611_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdtl',
            name='user_lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdtl',
            name='user_win',
            field=models.IntegerField(default=0),
        ),
    ]
