# Generated by Django 3.2.3 on 2021-06-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0048_auto_20210611_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdtl',
            name='timezone_user',
            field=models.CharField(default='Europe/London', max_length=200),
        ),
    ]
