# Generated by Django 3.2.3 on 2021-06-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0049_alter_userdtl_timezone_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdtl',
            name='img_user',
            field=models.ImageField(blank=True, default='media/profile/user.jpg', null=True, upload_to='media/profile'),
        ),
    ]
