# Generated by Django 3.2.3 on 2021-06-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0050_userdtl_img_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('messsage', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('contacted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
