# Generated by Django 3.2.3 on 2021-06-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0051_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messsage',
            new_name='message',
        ),
    ]
