# Generated by Django 3.2.3 on 2021-06-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0052_rename_messsage_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='media/Teams'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, default='media/Team/logo.png', null=True, upload_to='media/Teams'),
        ),
        migrations.AlterField(
            model_name='userdtl',
            name='twitch',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userdtl',
            name='twitter',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userdtl',
            name='youtube',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
