# Generated by Django 3.2.3 on 2021-06-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0053_auto_20210612_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_image', models.ImageField(upload_to='media/support')),
                ('about_info', models.TextField(blank=True, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=128, null=True)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('winner_bool', models.BooleanField(default=False)),
                ('access_name', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ladders',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
