# Generated by Django 3.2.3 on 2021-06-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0055_auto_20210613_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdtl',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
