# Generated by Django 3.2.3 on 2021-06-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0057_banuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladders',
            name='end_ladder',
            field=models.BooleanField(default=False),
        ),
    ]
