# Generated by Django 3.2.3 on 2021-06-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0058_ladders_end_ladder'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminoptions',
            name='home_video_heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='adminoptions',
            name='winner_list',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
