# Generated by Django 3.2.3 on 2021-06-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0059_auto_20210614_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdtl',
            name='forgot_access',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
