# Generated by Django 3.2.3 on 2021-06-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0060_userdtl_forgot_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='challenged_team',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
