# Generated by Django 3.2.3 on 2021-06-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0061_matches_challenged_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminoptions',
            options={'verbose_name': 'Web Management'},
        ),
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name': 'Game'},
        ),
        migrations.AlterModelOptions(
            name='ladders',
            options={'verbose_name': 'View Ladder'},
        ),
        migrations.AlterModelOptions(
            name='maps',
            options={'verbose_name': 'Map'},
        ),
        migrations.AlterModelOptions(
            name='matches',
            options={'verbose_name': 'Manage Matche'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'New'},
        ),
        migrations.AlterModelOptions(
            name='sliders',
            options={'verbose_name': 'Slider'},
        ),
        migrations.AlterModelOptions(
            name='userdtl',
            options={'verbose_name': 'User Detail'},
        ),
        migrations.AddField(
            model_name='adminoptions',
            name='about_banner',
            field=models.ImageField(blank=True, null=True, upload_to='media/News'),
        ),
        migrations.AddField(
            model_name='adminoptions',
            name='contact_banner',
            field=models.ImageField(blank=True, null=True, upload_to='media/Banner'),
        ),
        migrations.AddField(
            model_name='adminoptions',
            name='game_banner',
            field=models.ImageField(blank=True, null=True, upload_to='media/Banner'),
        ),
        migrations.AddField(
            model_name='adminoptions',
            name='ladder_banner',
            field=models.ImageField(blank=True, null=True, upload_to='media/Banner'),
        ),
        migrations.AddField(
            model_name='adminoptions',
            name='second_ladder_banner',
            field=models.ImageField(blank=True, null=True, upload_to='media/Banner'),
        ),
        migrations.AddField(
            model_name='adminoptions',
            name='team_background_banner',
            field=models.ImageField(blank=True, null=True, upload_to='media/Banner'),
        ),
    ]
