# Generated by Django 3.2.3 on 2021-06-14 12:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0062_auto_20210614_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminoptions',
            name='about_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminoptions',
            name='contact_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='ladders',
            name='playoff_info',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='ladders',
            name='rules',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='maps',
            name='rules',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='matches',
            name='members_list',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='Description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='dispute_text_1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='dispute_text_2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='team_1_report',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='team_2_report',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportteamone',
            name='msg',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportteamtwo',
            name='msg',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='rating_per_match',
            field=ckeditor.fields.RichTextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='team',
            name='streak',
            field=ckeditor.fields.RichTextField(blank=True, default='[]', null=True),
        ),
    ]
