# Generated by Django 3.2.3 on 2021-06-14 16:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0063_auto_20210614_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminoptions',
            name='notice_text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
