# Generated by Django 3.2.3 on 2021-06-14 17:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0064_adminoptions_notice_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminoptions',
            name='notice_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
