# Generated by Django 3.2.3 on 2021-06-14 17:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0065_alter_adminoptions_notice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminoptions',
            name='privacy_and_policy',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminoptions',
            name='term_and_condition',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
