# Generated by Django 3.2.3 on 2021-06-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0066_auto_20210614_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='members_list',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reportteamone',
            name='msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportteamtwo',
            name='msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='rating_per_match',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='team',
            name='streak',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
