# Generated by Django 3.2.3 on 2021-06-16 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0069_auto_20210615_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.CharField(blank=True, max_length=500, null=True)),
                ('video_title', models.CharField(blank=True, max_length=500, null=True)),
                ('admin_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_list', to='tlou.adminoptions')),
            ],
        ),
    ]
