# Generated by Django 3.2.3 on 2021-06-16 06:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tlou', '0070_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'New'},
        ),
        migrations.RenameField(
            model_name='adminoptions',
            old_name='about_banner',
            new_name='news_banner',
        ),
        migrations.RemoveField(
            model_name='adminoptions',
            name='home_notice',
        ),
        migrations.RemoveField(
            model_name='adminoptions',
            name='home_video',
        ),
        migrations.RemoveField(
            model_name='adminoptions',
            name='home_video_heading',
        ),
        migrations.AddField(
            model_name='adminoptions',
            name='about_background_banner',
            field=models.ImageField(blank=True, null=True, upload_to='media/News'),
        ),
        migrations.AddField(
            model_name='adminoptions',
            name='about_info_2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SocialList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(blank=True, max_length=400, null=True)),
                ('faicon', models.CharField(blank=True, default='fa-facebook', max_length=100, null=True)),
                ('options', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='tlou.adminoptions')),
            ],
        ),
    ]
